---
- hosts: api
  remote_user: deploy
  become: true
  vars:
    app: 'api'
  roles:
    - role: nginx-site

- hosts: admin
  remote_user: deploy
  become: true
  vars:
    app: 'admin'
  roles:
    - role: nginx-site

- hosts: survey
  remote_user: deploy
  become: true
  vars:
    app: 'survey'
  roles:
    - role: nginx-site
