name: CI

on:
  push:
    paths-ignore:
      - 'deployment/**'
      - 'docker/**'
      - 'apps/docs/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'deployment/**'
      - 'docker/**'
      - 'apps/docs/**'

permissions:
  contents: read

env:
  DB_TEST_SYSTEM_DATABASE: it24_system_test
  DB_TEST_SYSTEM_USERNAME: it24
  DB_TEST_SYSTEM_PASSWORD: Intake24!
  DB_TEST_FOODS_DATABASE: it24_foods_test
  DB_TEST_FOODS_USERNAME: it24
  DB_TEST_FOODS_PASSWORD: Intake24!

jobs:
  lint:
    name: Lint code

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - name: Repository checkout
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

  # API
  api-postgres:
    name: API (Node.js ${{ matrix.node-version }}, Postgres ${{ matrix.postgres-version }}, Redis ${{ matrix.redis-version }})

    runs-on: ubuntu-latest

    needs: lint

    env:
      DB_TEST_SYSTEM_HOST: localhost
      DB_TEST_SYSTEM_PORT: 5432
      DB_TEST_FOODS_HOST: localhost
      DB_TEST_FOODS_PORT: 5432

    strategy:
      matrix:
        node-version: [24.x]
        postgres-version: [18]
        redis-version: [8]

    services:
      postgres:
        image: postgres:${{ matrix.postgres-version }}
        env:
          POSTGRES_USER: it24
          POSTGRES_PASSWORD: Intake24!
          POSTGRES_DB: it24
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      redis:
        image: redis:${{ matrix.redis-version }}
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Repository checkout
        uses: actions/checkout@v6

      - name: Create foods/system databases
        run: |
          PGPASSWORD=${{ env.DB_TEST_FOODS_PASSWORD }} psql -h ${{ env.DB_TEST_FOODS_HOST }} -p 5432 -U ${{ env.DB_TEST_FOODS_USERNAME }} -c 'CREATE DATABASE ${{ env.DB_TEST_FOODS_DATABASE }};'
          PGPASSWORD=${{ env.DB_TEST_SYSTEM_PASSWORD }} psql -h ${{ env.DB_TEST_SYSTEM_HOST }} -p 5432 -U ${{ env.DB_TEST_SYSTEM_USERNAME }} -c 'CREATE DATABASE ${{ env.DB_TEST_SYSTEM_DATABASE }};'

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: API - use Github test environment file to build the workers with
        working-directory: apps/api
        run: cp __tests__/.env-test-gh .env

      - name: API - build for tests
        working-directory: apps/api
        run: pnpm build

      - name: API - use Github test environment file
        working-directory: apps/api
        run: cp ./__tests__/.env-test-gh ./__tests__/.env-test

      - name: Repo - unit tests
        run: pnpm test:unit

      - name: API - integration tests
        working-directory: apps/api
        run: pnpm test:integration

  # Admin client
  admin:
    name: Admin client (Node.js ${{ matrix.node-version }})

    runs-on: ubuntu-latest

    needs: lint

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - name: Repository checkout
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Admin client - build
        working-directory: apps/admin
        run: pnpm build

  # Survey client
  survey:
    name: Survey client (Node.js ${{ matrix.node-version }})

    runs-on: ubuntu-latest

    needs: lint

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - name: Repository checkout
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Survey client - type check
        working-directory: apps/survey
        run: pnpm type-check

      - name: Survey client - build
        working-directory: apps/survey
        run: pnpm build

  # CLI
  cli:
    name: CLI (Node.js ${{ matrix.node-version }})

    runs-on: ubuntu-latest

    needs: lint

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - name: Repository checkout
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: CLI - build
        working-directory: apps/cli
        run: pnpm build
